version: "2"
services:
  razilocms:
    build: ./
    labels:
      - "traefik.backend=razilocms"
      - "traefik.frontend.rule=Host:razilocms.docker.localhost"
    environment:
      - APACHE_SERVER_NAME=razilocms.docker.localhost
      - CONTAINER_TIMEZONE=Europe/London
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - PHP_LOG_ERRORS=On
    networks:
      - default
    volumes:
      - ./:/app
    cap_add:
      - SYS_TIME
      - SYS_NICE
networks:
  default:
    external:
      name: docker_docker-localhost
